# Angular 11 AzureDevOps pipeline

trigger:
  branches:
    include:
      - develop
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  ngBuildConfiguration: '--prod'
  ngWorkingDir: 'cfg-ng'

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: 'install'
    workingDir: '$(ngWorkingDir)'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '$(ngWorkingDir)'
    customCommand: 'run build -- $(ngBuildConfiguration)'