# Angular 11 AzureDevOps pipeline

trigger:
  branches:
    include:
      - develop
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  ngBuildConfiguration: '--prod'
  ngWorkingDir: 'cfg-ng'

steps:
- task: Npm@1
  displayName: 'Npm install'
  inputs:
    command: 'install'
    workingDir: '$(ngWorkingDir)'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '$(ngWorkingDir)'
    customCommand: 'run build -- $(ngBuildConfiguration)'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: angularPipelineArtifactProd
    targetPath: '$(ngWorkingDir)/dist'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(ngWorkingDir)/dist'
    ArtifactName: 'angularBuildArtifactProd'

- task: DeleteFiles@1
  displayName: 'Delete JUnit files'
  inputs:
    SourceFolder: '$(ngWorkingDir)/junit'
    Contents: 'TESTS*.xml'

- task: Npm@1
  displayName: 'Test angular'
  inputs:
    command: 'custom'
    workingDir: '$(ngWorkingDir)'
    customCommand: 'run test-headless'