# Angular 11 AzureDevOps pipeline

trigger:
  branches:
    include:
      - develop
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  ngBuildConfiguration: '--prod'
  ngWorkingDir: 'cfg-ng'

steps:
- task: Npm@1
  displayName: 'Npm install'
  inputs:
    command: 'install'
    workingDir: '$(ngWorkingDir)'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '$(ngWorkingDir)'
    customCommand: 'run build -- $(ngBuildConfiguration)'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: angularPipelineArtifactProd
    targetPath: '$(ngWorkingDir)/dist'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(ngWorkingDir)/dist'
    ArtifactName: 'angularBuildArtifactProd'

- task: DeleteFiles@1
  displayName: 'Delete JUnit files'
  inputs:
    SourceFolder: '$(ngWorkingDir)/junit'
    Contents: 'TESTS*.xml'

- task: Npm@1
  displayName: 'Test angular'
  inputs:
    command: 'custom'
    workingDir: '$(ngWorkingDir)'
    customCommand: 'run test-headless'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage Angular'
  condition: succeededOrFailed()
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(ngWorkingDir)/coverage/cobertura-coverage.xml'
    reportDirectory: '$(ngWorkingDir)/coverage'
    failIfCoverageEmpty: false

- task: PublishTestResults@2
  displayName: 'Publish Angular test results'
  condition: succeededOrFailed()
  inputs:
    searchFolder: $(System.DefaultWorkingDirectory)/$(ngWorkingDir)/junit
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
    failTaskOnFailedTests: false
    testRunTitle: 'Angular'
